#!/bin/sh
# File generated by ocamlbuild

cd '/home/atul/Desktop/ocaml codes/src'

rm -f q_arr.cmi
rm -f q_arr.cmx
rm -f q_arr.o
# Also clean the script itself
rm -f '/home/atul/Desktop/ocaml codes/src/_build/sanitize.sh'
